server:
  port: 8080

spring:
  application:
    name: bulletin-service

  #DB INFO
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ekwjd8978!
    url: jdbc:mysql://localhost:3306/noticedb?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&autoReconnect=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true

  #JPA/Hibernate
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        show-sql: true
    show-sql: 'true'